version: '3'
services:
  orders:
    build: ./orders
    ports:
    - '8080:3000'
    environment:
      - DB_USER=${PG_USER}
      - DB_PASS=${PG_PASSWORD}
      - DB_NAME=${PG_DB}
      - DB_PORT=${PG_PORT}
      - PORT=3000
    networks:
      - go-order
  payments:
    build: ./payments
    ports:
      - '8000:3000'
    environment:
      - DB_USER=${PG_USER}
      - DB_PASS=${PG_PASSWORD}
      - DB_NAME=${PG_DB}
      - DB_PORT=${PG_PORT}
      - PORT=3000
    networks:
      - go-order
  pgdb:
    image: postgres:14
    volumes:
      - /pgdata/go-orders:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=${PG_USER}
      - POSTGRES_PASSWORD=${PG_PASSWORD}
      - POSTGRES_DB=${PG_DB}
    networks:
      - go-order
networks:
  go-order:
    driver: bridge