version: '3'
services:
  orders:
    image: cosmtrek/air
    working_dir: /orders
    ports:
    - '8080:3000'
    environment:
      - FIRESTORE_PROJ_ID=${FIRESTORE_PROJ_ID}
      - PORT=3000
    volumes:
      - ./orders/:/orders
    networks:
      - go-order
networks:
  go-order:
    driver: bridge